// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nfccsabmyobekacffeoi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5mY2NzYWJteW9iZWthY2ZmZW9pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0NTg5MzAsImV4cCI6MjA3MDAzNDkzMH0.rCiQlPLGn3wNRttLX5SePX05zYZKnlnRc-BCgaPF-oU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});